name: 'database_universe'
description: 'Database Universe package for help you save any data in anywhere with high performance speed, easy feature and ready for scala business'
version: '1.1.2'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/General-Developer/database_universe'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'database'
  - 'database-universe'
  - 'sqlite'
  - 'encryption'
  - 'storage'
screenshots:
  - description: 'Database Universe Logo'
    path: 'assets/database_universe.png'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  analyzer: '>=7.1.0 <8.0.0'
  build: '^2.4.2'
  database_universe_flutter_libs: '^1.1.2'
  ffi: '>=2.1.3 <3.0.0'
  flutter:
    sdk: 'flutter'
  general_lib: '^0.0.66'
  js: '^0.7.1'
  meta: '^1.15.0'
  source_gen: '^2.0.0'
dev_dependencies:
  build_test: '^2.2.3'
  ffigen: '^15.0.0'
  flutter_lints: '^5.0.0'
  test: 'any'
  lints: '^5.0.0'
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '3.8.0'
project:
  type: ''
