name: 'database_universe_flutter_libs'
description: 'Database Universe package for help you save any data in anywhere with high performance speed, easy feature and ready for scala business'
version: '1.1.2'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/General-Developer/database_universe'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.10.0'
dev_dependencies:
  general_lib: '^0.0.66'
  lints: '^5.0.0'
  test: 'any'
dependencies:
  flutter:
    sdk: 'flutter'
flutter:
  plugin:
    platforms:
      android:
        package: 'general_developer.library.database_universe_flutter'
        pluginClass: 'DatabaseUniverseFlutterPlugin'
      ios:
        pluginClass: 'DatabaseUniverseFlutterLibsPlugin'
      macos:
        pluginClass: 'DatabaseUniverseFlutterLibsPlugin'
      linux:
        pluginClass: 'DatabaseUniverseFlutterLibsPlugin'
      windows:
        pluginClass: 'DatabaseUniverseFlutterLibsPlugin'
      web: null
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: ''
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
