name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  database_universe: '^1.0.5'
  general_lib: '^0.0.66'
  general_lib_flutter: '^0.0.41'
  path: '^1.9.0'
  general_framework: '^0.0.26'
  general_system_device: '^0.0.52'
  media_universe_flutter: '^0.0.1'
  packagex: '^0.0.85'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  build_runner: 'any'
  msix: '^3.16.8'
flutter:
  uses-material-design: true
dependency_overrides:
  database_universe:
    path: ../../package/database_universe
  database_universe_flutter:
    path: ../../package/database_universe_flutter
  pointycastle: '3.8.0'
  mime: '^2.0.0'

  media_universe:
    path: /home/galaxeus/.pub-cache/hosted/pub.dev/media_universe-0.0.0
funding: []
project:
  type: ''
packagex:
  name: 'example'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_build_arguments: []
  dart_compile_exe_arguments: []
  uploads:
    - platform_type: 'github'
      github_username: 'archivon-apps-stores'
      github_tag: 'release'
      github_is_org: false
      github_repository_name: 'example'
    - platform_type: 'supabase'
      supabase_folder_name: 'release'
    - platform_type: 'telegram'
      telegram_chats:
        - chat_id: '@slebew'
          message_thread_id: ''
  packages:
    - dart_target: 'example'
      flutter_target: 'main'
      dart_name: 'example'
      flutter_name: 'example'
      output_name: 'example'
msix_config:
  display_name: 'example'
  install_certificate: false
